import Foundation
import MachPatchBuilder
import MachPatchCore

public struct DebianPackageBuilder: Sendable {
    public init() {}

    public func build(
        project: PatchProject,
        buildRecord: PatchBuildRecord,
        dylibURL: URL
    ) throws -> DebianPackage {
        guard buildRecord.architecture == .arm64 else {
            throw PatchPackagingError.unsupportedDebianArchitecture(buildRecord.architecture)
        }
        guard let bundleIdentifier = project.target.bundleIdentifier,
            !bundleIdentifier.isEmpty
        else {
            throw PatchPackagingError.bundleIdentifierRequired
        }
        let dylib = try ArtifactPackagingValidator.validate(
            project: project,
            buildRecord: buildRecord,
            artifactURL: dylibURL,
            expectedRecordedPath: buildRecord.outputPath,
            expectedSHA256: buildRecord.provenance?.outputSHA256
        )
        let packageIdentifier = Self.packageIdentifier(
            targetBundleIdentifier: bundleIdentifier,
            outputName: project.build.outputName
        )
        let control = Self.control(
            packageIdentifier: packageIdentifier,
            displayName: project.projectName
        )
        let filterPlist = Self.filterPlist(bundleIdentifier: bundleIdentifier)
        let outputName = project.build.outputName
        let basePath = "./Library/MobileSubstrate/DynamicLibraries"
        let controlTar = try TarArchiveWriter.encode([
            TarEntry(
                path: "./control",
                contents: Data(control.utf8),
                mode: 0o644,
                isDirectory: false
            )
        ])
        let dataTar = try TarArchiveWriter.encode([
            TarEntry(path: "./Library/", contents: Data(), mode: 0o755, isDirectory: true),
            TarEntry(
                path: "./Library/MobileSubstrate/",
                contents: Data(),
                mode: 0o755,
                isDirectory: true
            ),
            TarEntry(
                path: "\(basePath)/",
                contents: Data(),
                mode: 0o755,
                isDirectory: true
            ),
            TarEntry(
                path: "\(basePath)/\(outputName).dylib",
                contents: dylib,
                mode: 0o755,
                isDirectory: false
            ),
            TarEntry(
                path: "\(basePath)/\(outputName).plist",
                contents: Data(filterPlist.utf8),
                mode: 0o644,
                isDirectory: false
            ),
        ])
        let archive = try ArArchiveWriter.encode([
            ArMember(name: "debian-binary", contents: Data("2.0\n".utf8)),
            ArMember(name: "control.tar", contents: controlTar),
            ArMember(name: "data.tar", contents: dataTar),
        ])
        return DebianPackage(
            filename: "\(outputName).deb",
            packageIdentifier: packageIdentifier,
            contents: archive
        )
    }

    private static func packageIdentifier(
        targetBundleIdentifier: String,
        outputName: String
    ) -> String {
        let raw = "\(targetBundleIdentifier).machpatch.\(outputName)".lowercased()
        let allowed = CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyz0123456789+.-")
        var sanitized = raw.unicodeScalars.map { allowed.contains($0) ? Character($0) : "-" }
        while sanitized.first.map({ $0.isLetter || $0.isNumber }) == false {
            sanitized.removeFirst()
        }
        while sanitized.last.map({ $0.isLetter || $0.isNumber }) == false {
            sanitized.removeLast()
        }
        return String(sanitized)
    }

    private static func control(packageIdentifier: String, displayName: String) -> String {
        let name = displayName.replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
        return """
            Package: \(packageIdentifier)
            Name: \(name)
            Version: 1.0.0
            Architecture: iphoneos-arm64
            Section: Tweaks
            Priority: optional
            Maintainer: MachPatch
            Description: Generated by MachPatch

            """
    }

    private static func filterPlist(bundleIdentifier: String) -> String {
        let escaped =
            bundleIdentifier
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return """
            {
                Filter = {
                    Bundles = (
                        "\(escaped)"
                    );
                };
            }

            """
    }
}
