import Foundation
import MachPatchBuilder
import MachPatchCore

public struct PatchSourceBundleBuilder: Sendable {
    public init() {}

    public func build(
        project: PatchProject,
        buildRecord: PatchBuildRecord,
        sourceURL: URL
    ) throws -> PatchSourceBundle {
        let source = try ArtifactPackagingValidator.validate(
            project: project,
            buildRecord: buildRecord,
            artifactURL: sourceURL,
            expectedRecordedPath: buildRecord.sourcePath,
            expectedSHA256: buildRecord.provenance?.generatedSourceSHA256
        )
        let projectJSON = try PatchProjectCodec.encode(project)
        let buildScript = Self.buildScript(project: project, buildRecord: buildRecord)
        let readme = Self.readme(project: project, buildRecord: buildRecord)

        return PatchSourceBundle(
            directoryName: "\(project.build.outputName)Source",
            files: [
                PackagedFile(relativePath: "patch.json", contents: projectJSON),
                PackagedFile(relativePath: "MachPatchGenerated.m", contents: source),
                PackagedFile(
                    relativePath: "build.sh",
                    contents: Data(buildScript.utf8),
                    isExecutable: true
                ),
                PackagedFile(relativePath: "README.md", contents: Data(readme.utf8)),
            ]
        )
    }

    private static func buildScript(
        project: PatchProject,
        buildRecord: PatchBuildRecord
    ) -> String {
        let outputName = project.build.outputName
        let deployment = project.build.minimumIOSVersion
        let arcFlag = project.build.enableARC ? " -fobjc-arc" : ""
        let common =
            "-isysroot \"$SDK\" -miphoneos-version-min=\(deployment)\(arcFlag) -fblocks -dynamiclib -Wall -Wextra -framework Foundation -framework UIKit -Wl,-install_name,@rpath/\(outputName).dylib"

        var lines = [
            "#!/bin/sh",
            "set -eu",
            "",
            "SCRIPT_DIR=\"$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\"",
            "CLANG=\"$(xcrun --find clang)\"",
            "SDK=\"$(xcrun --sdk iphoneos --show-sdk-path)\"",
            "SOURCE=\"$SCRIPT_DIR/MachPatchGenerated.m\"",
            "OUTPUT=\"$SCRIPT_DIR/\(outputName).dylib\"",
        ]

        switch buildRecord.architecture {
        case .arm64, .arm64e:
            let architecture = buildRecord.architecture.rawValue
            lines.append(
                "\"$CLANG\" -arch \(architecture) \(common) \"$SOURCE\" -o \"$OUTPUT\""
            )
        case .universal:
            lines.append(contentsOf: [
                "LIPO=\"$(xcrun --find lipo)\"",
                "ARM64_OUTPUT=\"$SCRIPT_DIR/\(outputName)-arm64.dylib\"",
                "ARM64E_OUTPUT=\"$SCRIPT_DIR/\(outputName)-arm64e.dylib\"",
                "\"$CLANG\" -arch arm64 \(common) \"$SOURCE\" -o \"$ARM64_OUTPUT\"",
                "\"$CLANG\" -arch arm64e \(common) \"$SOURCE\" -o \"$ARM64E_OUTPUT\"",
                "\"$LIPO\" -create \"$ARM64_OUTPUT\" \"$ARM64E_OUTPUT\" -output \"$OUTPUT\"",
                "rm -f \"$ARM64_OUTPUT\" \"$ARM64E_OUTPUT\"",
            ])
        }

        lines.append(contentsOf: [
            "",
            "echo \"Built $OUTPUT\"",
            "",
        ])
        return lines.joined(separator: "\n")
    }

    private static func readme(
        project: PatchProject,
        buildRecord: PatchBuildRecord
    ) -> String {
        """
        # \(project.projectName) Source Bundle

        Generated by MachPatch from the canonical `patch.json` project.

        ## Build

        Requirements: macOS, Xcode, and the iPhoneOS SDK.

        ```sh
        ./build.sh
        ```

        Output: `\(project.build.outputName).dylib` (\(buildRecord.architecture.rawValue), minimum iOS \(buildRecord.minimumIOSVersion)).

        ## Target identity

        - Bundle identifier: \(project.target.bundleIdentifier ?? "Not recorded")
        - Executable: \(project.target.executableName)
        - SHA-256: `\(project.target.executableSHA256)`
        - Selected image: \(project.target.selectedImage.relativePath) (\(project.target.selectedImage.kind.rawValue))
        - Selected image SHA-256: `\(project.target.selectedImage.executableSHA256)`
        - Recorded slice: \(project.target.selectedSlice.architecture.rawValue), CPU subtype \(project.target.selectedSlice.cpuSubtype)

        `MachPatchGenerated.m` is deterministic generated source. Edit `patch.json` in MachPatch and export a new source bundle instead of hand-editing generated code.
        """
    }
}

public struct PatchSourceArchiveBuilder: Sendable {
    public init() {}

    public func build(
        project: PatchProject,
        buildRecord: PatchBuildRecord,
        sourceURL: URL
    ) throws -> PatchSourceArchive {
        let bundle = try PatchSourceBundleBuilder().build(
            project: project,
            buildRecord: buildRecord,
            sourceURL: sourceURL
        )
        let archivedFiles = bundle.files.map { file in
            PackagedFile(
                relativePath: "\(bundle.directoryName)/\(file.relativePath)",
                contents: file.contents,
                isExecutable: file.isExecutable
            )
        }
        return PatchSourceArchive(
            filename: "\(bundle.directoryName).zip",
            contents: try ZipArchiveWriter.encode(archivedFiles)
        )
    }
}
